---
docker_folder:
            workplace: '/data/database-slave'
            config: '/data/database-slave/config'
            data: '/data/database-slave/data'
            dump: '/tmp/dump'
docker_container:
            name: 'slavedb'
            master_name: 'masterdb'
            master_host: 'localhost'
expose:
      port1: 3306