---
#Create folder for files: Dockerfile ...
- name: create workplace for Docker at {{ docker_folder.workplace }}
  file: name={{ docker_folder.workplace }} state=directory
- name: synchronize folder
  copy: src=files/ dest={{ docker_folder.workplace }}
#Create folder for files: my.cnf
- name: create workplace for Docker at {{ docker_folder.config }}
  file: name={{ docker_folder.config }} state=directory
- name: synchronize folder to {{ docker_folder.config }}
  copy: src=files/my.cnf dest={{ docker_folder.config }}
# Build image from Dockerfile
- name: check or build image
  docker_image:
              path={{ docker_folder.workplace }}
              name={{ db_slave.image_name }}
              docker_api_version="{{ docker_api_version }}"
              state=present
